### ISSUE TITLE
Double Click to Zoom Selects the Copyright Character

### ISSUE THREAD

**Issue by talllguy** [mpetroff/print-maps#1]
_Minor_ I noticed that while zooming in, the :copyright: Mapbox character is selected when double clicking the map to zoom.
![2015-02-09 09_02_08-print maps](https://cloud.githubusercontent.com/assets/1827881/6107627/7a09be38-b03a-11e4-967b-b00173854725.png)

**Comment by mpetroff** [comment]
This only happens in Chrome and is an upstream bug in Mapbox GL JS. As a temporary workaround, I disabled user select on the attribution element.

**Comment by mpetroff** [comment]
This was fixed upstream at some point.
