### ISSUE TITLE
Increase max width and height

### ISSUE THREAD

**Issue by antmoritz** [mpetroff/print-maps#10]
Trying to figure out how to change the max-width to 5906px and the max-height to 8268px. Any tips on how to proceed?

**Comment by antmoritz** [comment]
The site crashes when enter the max values accepted. Any recommendations on how to increase max size and prevent crashing?

**Comment by mpetroff** [comment]
Use a different computer; size limits are due to hardware limitations (or possibly OS / driver / browser limitations). There are no limits set in the Print Maps code.
