### ISSUE TITLE
Handling of attribution to adhere to TOS for Tile Companies

### ISSUE THREAD

**Issue by roblabs** [mpetroff/print-maps#12]
**Issue** — How to include attribution 

**Potential Solutions** 
1. Include basic attribution notes in `COPYING` or TOS for `print-maps`, and include in the footer of `index.html`
1. When downloading `map.png` or `map.pdf`, also download `COPYING` which has the modifications that suggests to include proper attribution.  For example, sites such as CodePen.io and Mapbox.com download a license when you down load a zip package from your account. 
1. Optionally write attributions to the `canvas`.  Change the UI to have a toggle.
 
Writing the Map canvas to PNG is handled in here

https://github.com/mpetroff/print-maps/blob/8c50e7c0ec4f6bdb1c9171722135fe14b7847f93/js/script.js#L360

---

Tile Companies and their Terms 

Mapbox 
* https://www.mapbox.com/help/how-attribution-works/
> Static and print maps need to be attributed in the same fashion as you would cite a photograph: in a textual description near the image.

Mapzen
* https://mapzen.com/rights/
> If you are using any of Mapzen services, you should use the following attribution statement:  © Mapzen, OpenStreetMap, and others

Klokantech
* https://openmaptiles.com/terms/
>For printed maps, images or video recording a similar attribution should be made in a clearly visible textual description near the map, in the same fashion as if you cite a photograph.

**Comment by mpetroff** [comment]
Good point. This project started as a weekend hack, so I never really considered including explicit attribution instructions (the need to give attribution seems obvious to me).

In 3fed2c04d6b8f2f8174b2951140374b825e394be, I included an attribution instructions section before the generate button and am now adding the attribution as the author metadata for PDFs.

**Comment by roblabs** [comment]
Thank you for including the attribution notes for users of the tool; it shows due diligence for the terms of service.  I've got further research into writing the scale and attribution directly into the PDF _cf._ #13.
