### ISSUE TITLE
Question on Copyright

### ISSUE THREAD

**Issue by hjrobinson** [mpetroff/print-maps#15]
If I don't use the mapstyle feature and use my own maps created with mapboxgl js do I need to purchase a plan?  I essentially just want to use the print features of the tool without the mapstyle component (which I can remove on my own).

**Comment by mpetroff** [comment]
I'm not entirely sure what you're asking. I didn't write Mapbox GL JS, and I don't know what plans you're referring to (I'm not selling anything). The code I've written (what's in this repository) is [MIT licensed](https://github.com/mpetroff/print-maps/blob/master/COPYING), so if you redistribute the code with or without modifications you need to keep the copyright statement with the code. However, the code license only covers the code, not the output produced by it.

The licensing of the output images is governed by the data provider, e.g. Mapbox or OpenMapTiles, depending on the style used. This is where the non-commercial use requirement and attribution requirements come from. You're certainly welcome to use whichever data provider you want.

**Comment by hjrobinson** [comment]
My mistake.  I incorrectly assumed this was an official Mapbox product and that all maps whether self-generated or otherwise might require some kind of subscription.  By the way thanks for the great plugin.

**Comment by mpetroff** [comment]
I have no affiliation with Mapbox. As far as I know, the only location of official Mapbox software is [their GitHub account](https://github.com/mapbox/).

When I originally made this tool, there was no easy way to generate print-resolution maps with OSM data, although Mapbox now has [an official way of doing so](https://www.mapbox.com/help/how-static-maps-work/).
