### ISSUE TITLE
Layer via mapboxgl.Map.addLayer() in rendered image missing

### ISSUE THREAD

**Issue by cschlueter** [mpetroff/print-maps#19]
Hi, this is great, but it doesn't seem to work with custom layers (e.g. GeoJSON information) on top of the map. Do you have any idea how to get a print of both the base layer map and one or more overlays?
I can't explain why that would be the case?! Somehow the data/layer must be in the canvas object, but the layers don't seem to be considered while exporting? 

Btw. it also doesn't work without your tooling by grabbing the image from the canvas via toDataURL.

**Comment by mpetroff** [comment]
If you're modifying the code, you're on your own. It must have something to do with how Mapbox GL JS handles additional layers.
