### ISSUE TITLE
404 for element causing chrome to spin

### ISSUE THREAD

**Issue by talllguy** [mpetroff/print-maps#2]
I noticed that the site seems to be continuously loading. I inspected the element in Chrome (Version 40.0.2214.111 m) and [this page appears to be 404](http://printmaps.org/lib/js/mapbox-gl.js.map) on my browser.

![2015-02-09 09_16_51-print maps](https://cloud.githubusercontent.com/assets/1827881/6107872/8dc2b176-b03c-11e4-9d77-1e3a5e16e24a.png)

**Comment by mpetroff** [comment]
Fixed in aec826797833b9560f3be391387e430cf6f3571a. What's really strange is that Firefox never tries to load this file.
