### ISSUE TITLE
Map corners don't completely render (satellite layer)

### ISSUE THREAD

**Issue by jessecrouch** [mpetroff/print-maps#21]
Sometimes the map's corners don't render completely when using a satellite layer. It's a sporadic behavior and during each map generation the result seems to be different. The squares that appear as lighter colored correspond directly with the Mapbox tiles.

I've tried applying timer delays to the various steps in createPrintMap->renderMap.once, but it doesn't seem to have any effect. Maybe a WebGL issue?

Any help appreciated, thanks!

![image](https://user-images.githubusercontent.com/202414/66595366-ac780000-eb4f-11e9-89cd-7ce1b92dacaa.png)

![image](https://user-images.githubusercontent.com/202414/66594732-8dc53980-eb4e-11e9-9010-5dcbff512c42.png)
![image](https://user-images.githubusercontent.com/202414/66594763-9d448280-eb4e-11e9-9829-c1ecac564adc.png)

**Comment by mpetroff** [comment]
The place to try to add a timeout would be inside the `load` callback function, as was done in d18430c1d51598c1e4f7fa7a45e6ccf1700c73ad to work around a bug in a previous version of Mapbox GL JS.

However, I wouldn't be surprised if this was a result of reaching the WebGL limit for maximum number of texture units.

I've never tried to use satellite imagery layers before.

**Comment by jessecrouch** [comment]
Thank you! Tried reapplying the timeout where you suggested and it works every time so far. Need to do some more testing (I've had different results in different environments). If it continues to work, would you like me submit the patch? Mine is an edge case and the delay it causes may not be suitable for everyone.

**Comment by pathmapper** [comment]
> the delay it causes may not be suitable for everyone

It could be that the [`idle`](https://docs.mapbox.com/mapbox-gl-js/api/#map.event:idle) event instead of the `load` event in https://github.com/mpetroff/print-maps/blob/69d4a24d90983049b345af17cda19bc3076875ce/js/script.js#L434 gives the expected result without the need for a timeout:

`renderMap.once('idle', function() { `

**Comment by mpetroff** [comment]
The `idle` event was switched to in 4715686fdf519fca377aa2a1bdaf2c6a4bef078d, so this should no longer be an issue.
