### ISSUE TITLE
Change  rendermap.once event to idle

### ISSUE THREAD

**Issue by stvno** [mpetroff/print-maps#22]
Related to #21 if you have transitions in your style they might not yet finished rendering when `map.on('load')` gets called, resulting in incomplete renders. using `map.on('idle')` fixes this.

Happens here: https://github.com/mpetroff/print-maps/blob/master/js/script.js#L434

**Comment by mpetroff** [comment]
This change was made in 4715686fdf519fca377aa2a1bdaf2c6a4bef078d.
