### ISSUE TITLE
Navigation control position

### ISSUE THREAD

**Issue by utilmind** [mpetroff/print-maps#24]
Hello! script.js contains code, which supposed to set up position for zoom buttons. However the code below does not works.

```
    map.addControl(new mapboxgl.NavigationControl({
        position: 'top-left'
    }));
```
Consider to switch to the following instead:

`    map.addControl(new mapboxgl.NavigationControl(), "top-left");
`

**Comment by mpetroff** [comment]
Thanks for pointing this out. It used to work but broke sometime in the past five years with a Mapbox GL JS update. Since the exact position doesn't matter, I just removed the location specification.
