### ISSUE TITLE
printing with details without zooming

### ISSUE THREAD

**Issue by Xsmael** [mpetroff/print-maps#25]
Hi,
it will be very nice to be able to printing with details for instance of zoomlevel 12 when the view is at zoomlevel 11  so that we can have a larger coverage but with good details and resolution. 

As manual alternative i'll have to generate separate adjacent images and then join them together with an editting software, but it'll be amazing to be able to do it right away.

**Comment by mpetroff** [comment]
You can already do this; just change the dimensions. Doubling the width and height has the exact same effect as keeping the original width and height and stitching together four separate sub-images.

**Comment by Xsmael** [comment]
Oh waw, that's really cool! 
Thanks.
