### ISSUE TITLE
Exporting custom styles

### ISSUE THREAD

**Issue by iskandari** [mpetroff/print-maps#7]
This is a great tool. Could instructions be included on how to export your own style in addition to the standard Mapbox styles? 

For example, if my style is: `mapbox://styles/testuser/ciyb84q3s000q2sqlyr5bz53u`

What should I change in the code to export it?

**Comment by mpetroff** [comment]
Here's where the existing styles are:
https://github.com/mpetroff/print-maps/blob/master/index.html#L55
