### ISSUE TITLE
IE 11 prints PDF when PNG is selected

### ISSUE THREAD

**Issue by keyofj** [mpetroff/print-maps#8]
When using IE 11 and your test page when picking to print PNG a pdf is created instead. The PDF that is created is also not sized correctly. When zoomed to 100% it looks like a thumbnail print. You have to zoom to 1900%+ to get it close to the size it was on screen.

Thoughts

**Comment by mpetroff** [comment]
IE 11, unlike Firefox and Chrome, doesn't support the way I was reading the radio button values, which made the script behave as if PDF and millimeters were always selected (which is why it wasn't sized correctly). I fixed this in 8c50e7c0ec4f6bdb1c9171722135fe14b7847f93.
