### ISSUE TITLE
map.remove() doesn't remove the map

### ISSUE THREAD

**Issue by PennyBeames** [mpetroff/print-maps#9]
First things first, this is such a useful tool. Thank you thank you thank you.

Did you have a problem getting renderMap.remove(); to actually remove renderMap? I have created an application that depends on a few versions of the same map (a display version, a print map version that opens when a modal is activated, and then the hidden map to generate the png/pdf). I call .remove(); on the print map when the modal is closed. This function successfully removes all of the print map DOM elements so from the way it looks on the screen and in the Elements view in Chrome inspector, the old print map is gone. But when I open the print map modal again to generate a new renderMap, all of my previous print maps reappear. 

I'm also getting a ton of Error: Error at Actor.receive (actor.js:69) but nothing in the actor.js explains what this error is about.

Did you have trouble with this when you built print-maps?

**Comment by mpetroff** [comment]
Unfortunately, I have never seen an issue like this before and don't have any idea why it would happen. Sorry I can't be of more help.

**Comment by PennyBeames** [comment]
No, it's okay. I asked around and it looks like I have a reference sharing issue somewhere in the print map section of the code. It's preventing remove() from functioning properly... back to debugging. 

Thanks again for a killer application, though. Once I get my version working it'll be slick!
